=== NGUYENDUONG5G/jacamo/src/main/resources/xml/os.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:moise="http://moise.sourceforge.net/os"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://moise.sourceforge.net/os">

    <xsd:element name="organisational-specification" type="moise:osType"/>

    <xsd:complexType name="osType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties"               type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="structural-specification" type="moise:ssType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="functional-specification" type="moise:fsType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="normative-specification"  type="moise:nsType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="os-version" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ssType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="role-definitions">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="role" type="moise:roleDefType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="link-types">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link-type">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="group-specification" type="moise:groupSpecificationType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="scheme">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
                        <xsd:element maxOccurs="1" minOccurs="1" name="goal" type="moise:goalDefType"/>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="mission" type="moise:missionType"/>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" ref="moise:failure"/>
                    </xsd:sequence>

                    <xsd:attribute name="id" type="xsd:string"/>
                    <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"> </xsd:attribute -->
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="missionType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="preferred">
                <xsd:complexType>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="nsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="norm">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required" />
                    <xsd:attribute name="condition" type="xsd:string" use="optional" />
                    <xsd:attribute name="role" type="xsd:string" use="required"/>
                    <xsd:attribute name="type" type="moise:deonticType" use="required"/>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                    <xsd:attribute name="time-constraint" type="xsd:string" use="optional"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="npl-norms" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="propertiesType">
        <xsd:sequence maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="property">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                    <xsd:attribute name="value" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="roleDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="extends">
                <xsd:complexType>
                    <xsd:attribute name="role" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="scopeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="intra-group"/>
            <xsd:enumeration value="inter-group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="cardinalityObjectType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="role"/>
            <xsd:enumeration value="group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="groupSpecificationType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="roles">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="role">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string"/>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="links">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string"/>
                                <xsd:attribute name="to" type="xsd:string"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                                <xsd:attribute default="intra-group" name="scope"             type="moise:scopeType"/>
                                <xsd:attribute default="false"       name="extends-subgroups" type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="unbounded" minOccurs="0" name="subgroups">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0"
                            name="include-group-specification">
                            <xsd:complexType>
                                <xsd:attribute name="uri" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="group-specification" type="moise:groupSpecificationType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="1" minOccurs="0" name="formation-constraints">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="cardinality">
                            <xsd:complexType>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="object" type="moise:cardinalityObjectType" use="required"/>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="compatibility">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string" use="required"/>
                                <xsd:attribute name="to" type="xsd:string" use="required"/>
                                <xsd:attribute default="intra-group" name="scope"        type="moise:scopeType"/>
                                <xsd:attribute default="false" name="extends-subgroups"  type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
        <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"/ -->
    </xsd:complexType>

    <xsd:complexType name="planType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal" type="moise:goalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="operator" type="moise:planOperatorType" use="required"/>
        <xsd:attribute name="success-rate" type="xsd:double" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="goalDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="argument"   type="moise:argumentType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="depends-on" type="moise:dependOnType"/>
            <xsd:element maxOccurs="1"         minOccurs="0" name="plan"       type="moise:planType"/>
        </xsd:sequence>
        <xsd:attribute name="id"       type="xsd:string"             use="required"/>
        <xsd:attribute name="min"      type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="ds"       type="xsd:string"             use="optional"/>
        <xsd:attribute name="type"     type="moise:goalType"/>
        <xsd:attribute name="ttf"      type="xsd:string"             use="optional"/>
        <xsd:attribute name="location" type="xsd:string"             use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="argumentType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="optional"/>
        <xsd:attribute name="arity" type="xsd:integer" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="dependOnType">
        <xsd:attribute name="goal" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="planOperatorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="sequence"/>
            <xsd:enumeration value="choice"/>
            <xsd:enumeration value="parallel"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goalType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="performance"/>
            <xsd:enumeration value="achievement"/>
            <xsd:enumeration value="maintenance"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="deonticType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="obligation"/>
            <xsd:enumeration value="permission"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="argument" type="moise:argumentType" />
    <xsd:element name="condition" type="xsd:string" />

    <xsd:element name="recoveryact" type="moise:recoveryActType" />
    <xsd:complexType name="recoveryActType">
        <xsd:attribute name="scheme" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:element name="error" type="moise:errorType" />
    <xsd:complexType name="errorType">
        <xsd:sequence>
            <xsd:element ref="moise:condition" minOccurs="1" maxOccurs="1" />
            <xsd:element ref="moise:argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element ref="moise:recoveryact" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:element name="failure" type="moise:failureType" />
    <xsd:complexType name="failureType">
        <xsd:sequence>
            <xsd:element ref="moise:error" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="optional" />
        <xsd:attribute name="goal" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:schema>

=== NGUYENDUONG5G/jacamo/examples/my-example/src/org/my-org.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="cleaning_org"
    os-version="1.1"
    xmlns='http://moise.sourceforge.net/os'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://moise.sourceforge.net/os
                        https://moise-lang.github.io/xml/os.xsd' >

    <structural-specification>
        <role-definitions>
            <role id="cleaner" />
            <role id="supervisor" />
        </role-definitions>

        <group-specification id="team">
            <roles>
                <role id="cleaner" min="1" max="5" />
                <role id="supervisor" min="0" max="1" />
            </roles>
            <formation-constraints>
                <compatibility from="cleaner" to="supervisor" scope="intra-group" bi-dir="true"/>
            </formation-constraints>
        </group-specification>
    </structural-specification>

    <functional-specification>
        <scheme id="cleaning_scheme">
            <goal id="maintain_cleanliness">
                <plan operator="parallel">
                    <goal id="observe_environment">
                        <plan operator="sequence">
                            <goal id="locate_next_target" />
                            <goal id="move_to_target" />
                        </plan>
                    </goal>
                    <goal id="clean_room" />
                    <goal id="battery_loaded" />
                </plan>
            </goal>

            <mission id="cleaner_mission" min="1" max="5">
                <goal id="observe_environment" />
                <goal id="locate_next_target" />
                <goal id="move_to_target" />
                <goal id="clean_room" />
                <goal id="battery_loaded" />
            </mission>
        </scheme>
    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="cleaner" mission="cleaner_mission" />
    </normative-specification>

</organisational-specification>

=== NGUYENDUONG5G/jacamo/examples/my-example-test/src/org/my-org.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="delivery_org"
    os-version="1.1"
    xmlns='http://moise.sourceforge.net/os'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://moise.sourceforge.net/os
                        https://moise-lang.github.io/xml/os.xsd' >

    <structural-specification>
        <role-definitions>
            <role id="dispatcher" />
            <role id="delivery_robot" />
        </role-definitions>

        <group-specification id="team">
            <roles>
                <role id="dispatcher" min="1" max="1" />
                <role id="delivery_robot" min="1" max="10" />
            </roles>
            <formation-constraints>
                <compatibility from="dispatcher" to="delivery_robot" scope="intra-group" bi-dir="true"/>
            </formation-constraints>
        </group-specification>
    </structural-specification>

    <functional-specification>
        <scheme id="delivery_scheme">
            <goal id="deliver_success">
                <plan operator="sequence">
                    <goal id="pickup_package" />
                    <goal id="transit_to_delivery" />
                    <goal id="handover_package" />
                    <goal id="complete_cycle" />
                </plan>
            </goal>

            <mission id="delivery_mission" min="1" max="10">
                <goal id="deliver_success" />
                <goal id="pickup_package" />
                <goal id="transit_to_delivery" />
                <goal id="handover_package" />
                <goal id="complete_cycle" />
            </mission>
        </scheme>
    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="delivery_robot" mission="delivery_mission" />
    </normative-specification>

</organisational-specification>

=== NGUYENDUONG5G/jacamo/examples/coffee-maker/src/org/coffee-org.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="coffee_org"
    os-version="1.1"
    xmlns='http://moise.sourceforge.net/os'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://moise.sourceforge.net/os
                        https://moise-lang.github.io/xml/os.xsd' >

    <structural-specification>
        <role-definitions>
            <role id="coffee_maker_role" />
            <role id="water_boiler_role" />
        </role-definitions>

        <group-specification id="coffee_team">
            <roles>
                <role id="coffee_maker_role" min="1" max="1" />
                <role id="water_boiler_role" min="1" max="1" />
            </roles>
            <formation-constraints>
                <compatibility from="coffee_maker_role" to="water_boiler_role" scope="intra-group" bi-dir="true"/>
            </formation-constraints>
        </group-specification>
    </structural-specification>

    <functional-specification>
        <scheme id="coffee_scheme">
            
            <goal id="prepare_ingredients">
                <plan operator="parallel">
                    <goal id="boil_water" />
                    <goal id="grind_beans" />
                </plan>
            </goal>

            <mission id="coffee_making_mission" min="1" max="1">
                <goal id="grind_beans" />
            </mission>

            <mission id="water_boiling_mission" min="1" max="1">
                <goal id="boil_water" />
            </mission>
        </scheme>
    </functional-specification>

    <normative-specification>
        <norm id="norm_coffee_maker" type="obligation" role="coffee_maker_role" mission="coffee_making_mission" />
        <norm id="norm_water_boiler" type="obligation" role="water_boiler_role" mission="water_boiling_mission" />
    </normative-specification>

</organisational-specification>

=== NGUYENDUONG5G/jacamo/examples/fault-tolerant-therapy/src/org/therapy-os.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl"?>

<organisational-specification
    id="medical_therapy"
    os-version="1.1"
    xmlns='http://moise.sourceforge.net/os'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://moise.sourceforge.net/os https://moise-lang.github.io/xml/os.xsd'>

    <structural-specification>
        <role-definitions>
            <role id="patient" />
            <role id="doctor" />
            <role id="pharmacist" />
        </role-definitions>

        <group-specification id="therapy_group">
            <roles>
                <role id="patient" min="1" max="1" />
                <role id="doctor" min="1" max="1" />
                <role id="pharmacist" min="1" max="1" />
            </roles>
            <links>
                <link from="doctor" type="authority" to="patient" scope="intra-group" />
                <link from="patient" type="communication" to="doctor" scope="intra-group" />
                <link from="doctor" type="communication" to="pharmacist" scope="intra-group" />
                <link from="pharmacist" type="communication" to="patient" scope="intra-group" />
            </links>
        </group-specification>
    </structural-specification>

    <functional-specification>
        <scheme id="therapy_sch">
            <goal id="therapy">
                <plan operator="sequence">
                    <goal id="cpf">
                        <plan operator="sequence">
                            <goal id="consult" />
                            <goal id="prescribe" />
                            <goal id="fill_prescription" />
                        </plan>
                    </goal>
                    <goal id="follow_therapy" ttf="5 day" />
                </plan>
            </goal>

            <mission id="mPatient" min="1" max="1">
                <goal id="consult" />
                <goal id="follow_therapy" />
            </mission>
            <mission id="mDoctor" min="1" max="1">
                <goal id="prescribe" />
            </mission>
            <mission id="mPharmacist" min="1" max="1">
                <goal id="fill_prescription" />
            </mission>


            <failure id="f_follow_therapy" goal="follow_therapy">
                <error id="lost_symptoms">
                    <condition signal="lost_symptoms" />
                    <argument id="patient_id" arity="1" />
                    <argument id="cleared_day" arity="1" />
                    <argument id="early_recovery_reason" arity="1" />
                    <recoveryact scheme="reconsult_scheme" />
                </error>

                <error id="no_delivery">
                    <condition signal="delivery_failed" />
                    <argument id="prescription_id" arity="1" />
                    <argument id="delivery_address" arity="1" />
                    <argument id="delivery_attempt" arity="1" />
                    <argument id="failure_cause" arity="1" />
                    <recoveryact scheme="redelivery_scheme" />
                </error>
            </failure>
        </scheme>


        <scheme id="reconsult_scheme">
            <goal id="reconsult_goal">
                <plan operator="sequence">
                    <goal id="review_symptoms" />
                    <goal id="adjust_therapy" />
                </plan>
            </goal>

            <mission id="mDoctorReconsult" min="1" max="1">
                <goal id="review_symptoms" />
                <goal id="adjust_therapy" />
            </mission>
        </scheme>
    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="patient" mission="mPatient" />
        <norm id="n2" type="obligation" role="doctor" mission="mDoctor" />
        <norm id="n3" type="obligation" role="pharmacist" mission="mPharmacist" />
        <norm id="n4" type="obligation" role="doctor" mission="mDoctorReconsult" />
    </normative-specification>
</organisational-specification>
